### PR TITLE
Support Date for equal, in, and between along with nullable prop

### PR DESCRIPTION
**Pull request by Ibrahemkhalil**
Type = "date" 
Doesn't work properly when matching against DateTime properties when the time portion is not 12:00 am.
Now it's fixed for Equals, In, and Between operators along with supporting nullable properties.

### CODE REVIEW

**Comment by Ibrahemkhalil** [comment]
@tghamm This test was failing from the beginning :)
What shall I do?

**Comment by Ibrahemkhalil** [comment]
@tghamm for your kind action.

**Comment by tghamm** [comment]
@Ibrahemkhalil we could support another multitarget for .net6 if we wanted to to directly support those structs if anyone was interested in tackling the PR.  Thanks for these fixes, will review and get them merged assuming they look good!

**Comment by tghamm** [comment]
@Ibrahemkhalil looks like you removed support for .NET45. .NET 45 is ancient, but I don't have a good sense of whether anyone is still actually using that target.  I'm a little hesitant to remove it.  People using this library are presumably also still using jQuery... or at least some of them are.  Thoughts?

**Comment by Ibrahemkhalil** [comment]
@tghamm you can add it again, it will still work. Sorry for this.

**Comment by tghamm** [comment]
Cool no problem!  Thanks again for the effort!  I'll review in detail asap!

**Pull request merged**
