### PR TITLE
Added toggle to enable case sensitive comparisons

### PR DESCRIPTION
**Pull request by Ilanlido**
Fixed object comparison bugs by converting to string 
Updated dictionary access reflaction to use Get_Item instead of Index (mongo driver supports only Get_Item)

### CODE REVIEW

**Comment by Ilanlido** [comment]
Need to also add more support for object comparisons

**Comment by tghamm** [comment]
Is your use case here against a MongoDB?  If so, mind providing some details on a basic implementation?  I'm not a Mongo user but would be interested in adding a few integration tests if that's the target destination the same way I targeted EFCore just to make sure I could test locally that changes aren't breaking for either driver user.

**Comment by Ilanlido** [comment]
Yes, The dictionary support is mainly for mongo. You're right, ill take a look at what you did with EFCore to add more tests. Thanks for the fast responses!!

**Comment by Ilanlido** [comment]
@tghamm Understood, is it possible to merge these PRs and i'll add a local test for mongo in the weekend? Thanks!

**Comment by tghamm** [comment]
@Ilanlido yeah, all 3 ready to go?  Thanks!

**Comment by Ilanlido** [comment]
Yes, thank you!

**Pull request merged**
