### PR TITLE
Support Guid and Nullable Guid Data Types

### PR DESCRIPTION
**Pull request by Ibrahemkhalil**
Support GUID data type.

### CODE REVIEW

**Comment by tghamm** [comment]
Hi @Ibrahemkhalil thank you for the PR.  Can you add supporting test cases for the changes you made?  Thank you!

**Comment by Ibrahemkhalil** [comment]
> Hi @Ibrahemkhalil thank you for the PR. Can you add supporting test cases for the changes you made? Thank you!

Tests have been updated along with support for [Contains / EndsWith / BeginsWith / Equals]

**Comment by tghamm** [comment]
@Ibrahemkhalil awesome thank you.  It looks like you've addressed the previous issue that `Guid` inclusion caused (a regression where `ToString` was executed on all types, preventing `linq-to-sql` from translating properly).  I'll give it a whirl in the next day or two and if all checks out I'll put out a new release.  Thanks again for the effort, very cool!

**Comment by tghamm** [comment]
@Ibrahemkhalil I just made a very minor commit to master that will ensure that when code coverage is run against a PR it's assessed against the PR and not against master.  The version of `coveralls.net` I was using was VERY old so I bumped it to a version that will tag your PR as a PR.  As a favor, if you don't mind, pull the latest from my master into your branch and update the PR, it'll give accurate code coverage and a passing build in the checks for the PR.  Apologies for the inconvenience!  I'm reviewing over the weekend - very much appreciate the contribution!

**Comment by tghamm** [comment]
@Ibrahemkhalil sorry for the back and forth.  I've updated CI to properly reflect that there are a couple of test case failures in the PR. Basically the custom operator `Guid` work I added needs to be removed and the tests need to be corrected in a couple of cases.  You can remove the code associated with them here:

https://github.com/tghamm/dynamic-linq-query-builder/blob/a726703dc574ebf9f84c6495070706d45d2e18b2/Castle.DynamicLinqQueryBuilder.Tests/CustomOperatorsTests.cs#L74-L269

**Comment by Ibrahemkhalil** [comment]
@tghamm no issue. You may check now.

**Comment by tghamm** [comment]
@Ibrahemkhalil thank you. I'll give it a closer look in a bit but I think this probably rounds it out.  Good note on date formatting, that is worth a revisit.

**Comment by tghamm** [comment]
@Ibrahemkhalil new version has been released, thanks again for your contribution!

**Pull request merged**
